#ifndef __DUNGEONEER_DATATYPES_H__
#define __DUNGEONEER_DATATYPES_H__

#include <stdint.h>

#ifndef BOOL
typedef	uint32_t BOOL;
#endif

#ifndef FALSE
#define FALSE	0
#endif

#ifndef TRUE
#define TRUE	1
#endif

typedef unsigned char	UCHAR;
typedef signed char		SCHAR;
typedef uint8_t			UINT8;
typedef int8_t			SINT8;
typedef uint16_t		UINT16;
typedef int16_t			SINT16;
typedef	uint32_t		UINT32;
typedef int32_t			SINT32;


#endif

